default:
  lines:
    - "{prefix} {first_name} {last_name}"
    - "{address1}"
    - "{address2}"
    - "{zip} {city}"
    - "{country}"
  uppercase_last_n_lines: 1

DE:
  lines:
    - "{prefix} {last_name}"
    - "{address1}"
    - "{address2}"
    - "{zip} {city}"
    - "Germany"
  uppercase_last_n_lines: 2

FR:
  lines:
    - "{prefix} {first_name} {last_name}"
    - "{address1}"
    - "{address2}"
    - "{zip} {city}"
    - "France"
  uppercase_last_n_lines: 2

UA:
  lines:
    - "{first_name} {last_name}"
    - "{address1}"
    - "{address2}"
    - "{city}"
    - "{zip}"
    - "UKRAINE"
  uppercase_last_n_lines: 2

PF:
  lines:
    - "{prefix} {first_name} {last_name}"
    - "{address1}"
    - "{address2}"
    - "{zip} {city} {state}"
    - "FRENCH POLYNESIA"
